trigger:
- main

parameters:
- name: package_version
  displayName: Package Version
  type: string
  default: 1.1

variables:
- name: PACKAGE_VERSION
  value: ${{ parameters.package_version }}.$(Build.BuildId)
- name: vmImageName
  value: 'ubuntu-22.04'

stages:
- stage: Build
  displayName: Build Package
  jobs:
      - job:
        displayName: ${{ variables.vmImageName }}
        pool:
          vmImage: $(vmImageName)
        strategy:
          matrix:
            Python38:
              python.version: '3.8'              
              env_file: 'environment_py38.yml'
              
        steps:
        - bash: echo "##vso[task.prependpath]$CONDA/bin"
          displayName: Add conda to PATH
      
        - script: conda env update --name base --file $(env_file)
          displayName: Create Anaconda environment
      
        - bash: |
            python setup.py bdist_wheel
          displayName: Build wheel

        - script: 'pip install twine keyring artifacts-keyring'
          displayName: Install publishing prerequisites
  
        - task: TwineAuthenticate@1
          inputs:
            artifactFeed: 'Warn-on-Forecast/wofs-post'
          displayName: Authenticate Twine

        - script: |
            python -m twine upload -r wofs-post --config-file $(PYPIRC_PATH) --skip-existing dist/*.whl
          displayName: Publish Package

        - task: GithubRelease@1 
          displayName: 'Create GitHub Release'
          inputs:
            gitHubConnection: WarnOnForecast-Github
            repositoryName: WarnOnForecast/wofs_ml_severe
            isPreRelease: false
            tagSource: userSpecifiedTag
            assets: dist/*.whl
            tag: $(PACKAGE_VERSION)-py$(python.version)
