name: monte_python
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.15
  - pip=21.1
  - numpy=1.22.4  
  - scikit-image>=0.19
  - xarray>=0.18 
  - scikit-learn=1.0.2
  - numba=0.56.4
   
