name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.3.2
  - scikit-image>=0.19
  - xarray>=0.18  
  - pandas>=1.3.0
  - scikit-learn=1.0.2
  - scikit-learn-intelex=2023.0.1
  - pip:
    - tensorflow==2.15.0
    - jax==0.4.24
    - jaxlib==0.4.24
    - imblearn
    - hyperopt
    - lightgbm
