#######################################
# MACHINE LEARNING CONFIGURATION YAML
#######################################

UH_THRESHS : [180]
WIND_THRESHS : [40]
HAIL_THRESHS : [1.0]

# (in grid points) 
NMEP_SIZES : [3]

BASELINE_VARS : 
    tornado : 'uh_nmep_>180_3km__prob_max'
    severe_hail : 'hail_nmep_>1.0_3km__prob_max'
    severe_wind : 'wind_nmep_>40_3km__prob_max'
    
ML_MODEL_PATH : '/work/mflora/ML_DATA/MODEL_SAVES/'

RENAME_TARGETS : 
    matched_to_severe_hail_0km : 'Severe Hail' 
    matched_to_tornado_0km     : 'Tornado' 
    matched_to_severe_wind_0km : 'Severe Wind'
                    
MODEL_NAMES : ['RandomForest', 
               'LogisticRegression', 
               'Baseline'
              ]
TARGETS : ['tornado', 
           'severe_hail', 
           'severe_wind'
          ] 

ENS_VARS  : [ 'uh_0to2_instant',
              'uh_2to5_instant',
              'wz_0to2_instant',
              'comp_dz',
              'ws_80',
              'w_up',
              'hailcast',
              'w_1km',
              'w_down',
              '10-500m_bulkshear',
              'div_10m',
              'buoyancy',
              'ctt',
              'dbz_3to5', 
              'dbz_1to3', 
]

ENV_IN_ENS_VARS : []

ENV_VARS : [
              'theta_e',
              'u_10',
              'v_10',
              'temperature_850',
              'temperature_700',
              'temperature_500',
              'td_850',
              'td_700',
              'td_500',
              'mid_level_lapse_rate',
              'low_level_lapse_rate',
              'geo_hgt_850',
              'geo_hgt_500',
              'geo_hgt_700',
]

SVR_VARS : [ 'srh_0to1',
             'srh_0to3',
             'cape_ml',
             'cin_ml',
             'shear_u_0to6',
             'shear_v_0to6',
             'shear_u_0to1',
             'shear_v_0to1',
             'lcl_ml',
           ]

ENS_MIN_VARS : [ 'ctt',
             'buoyancy',
             'div_10m',
             'w_down'
             ]

MORPHOLOGICAL_FEATURES : [
                          'area',
                          'eccentricity',
                          'extent',
                          'orientation',
                          'minor_axis_length',
                          'major_axis_length', 
                          'label', 
                          ]


# TOP PREDICTORS FOR THE DIFFERENT HAZARDS. 
# Based on Shapley and LR coefficients. 
# Tornado:
                   # 0-2 vert. vort (90th)
                   # hail size (90th)
                   # 2-5 km UH 
                   # Composite Refl
                   # ML CAPE 
                   
                   # Hail: 
                   # 3-5 km Max Refl.
                   # Updraft 
                   # Major axis length 
                   # Composite Refl. (repeat)
                   # 0-3 km Lapse Rate 
                   
                   # Wind:
                   # 80-m wind speed 
                   # Composite Refl. (repeat) 
                   # Minor axis length 
                   # 0-2 vert vort (repeat) 
                   # 500-700 mb lapse rate. 



FEATURE_SUBSET_DICT :  
                   'wz_0to2__time_max__amp_ens_mean' : 'vert_vort' 
                   'hailcast__time_max__amp_ens_mean' : 'hail_size'
                   'uh_2to5__time_max__amp_ens_mean' : 'uh'  
                   'comp_dz__time_max__amp_ens_mean' : 'comp_refl'
                   'cape_ml__ens_mean__spatial_mean' : 'cape' 
                   
                   'dbz_3to5__time_max__amp_ens_mean' : 'dbz_3to5'
                   'w_up__time_max__amp_ens_mean' : 'updraft'
                   
                   'ws_80__time_max__amp_ens_mean' : '80m_wind_spd'
                   'major_axis_length' : 'major_axis_length' 
                   'minor_axis_length' : 'minor_axis_length' 
                   'low_level_lapse_rate__ens_mean__spatial_mean' : '0-3km_lapse_rate' 
                   'mid_level_lapse_rate__ens_mean__spatial_mean' : '500-700mb_lapse_rate'
                 

ROUNDING : 
    'vert_vort' : 4
    'hail_size' : 2
    'uh' : 0
    'comp_refl' : 0 
    'cape' : 0
    'dbz_3to5' : 0 
    'updraft': 1 
    '80m_wind_spd' : 0
    'major_axis_length' : 0 
    'minor_axis_length' : 0
    '0-3km_lapse_rate' : 2
    '500-700mb_lapse_rate' : 2



RESAMPLE_DICT : 
    first_hour : 
        tornado       :
            RandomForest      : 'under'
            LogisticRegression: 'under'
            XGBoost           : 'under'
        severe_hail   :
            RandomForest      : 'under'
            LogisticRegression: 'under'
            XGBoost           : None
        severe_wind :
            RandomForest      : None
            LogisticRegression: 'under'
            XGBoost'           : None

    second_hour: 
        tornado :
            RandomForest      : 'under'
            LogisticRegression: None
            XGBoost           : 'under'
        severe_hail :
            RandomForest      : None
            LogisticRegression: None
            XGBoost           : None
        severe_wind :
            RandomForest      : 'under'
            LogisticRegression: None
            XGBoost           : None
       
