#######################################
# MACHINE LEARNING CONFIGURATION YAML
#######################################

UH_THRESHS : [180]
WIND_THRESHS : [40]
HAIL_THRESHS : [1.0]

# (in grid points) 
NMEP_SIZES : [0]

BASELINE_VARS : 
    tornado_severe_0km : 'uh_nmep_>180_0km__prob_max'
    hail_severe_0km : 'hail_nmep_>1.0_0km__prob_max'
    wind_severe_0km : 'wind_nmep_>40_0km__prob_max'
    
ML_MODEL_PATH : '/work/mflora/ML_DATA/NEW_ML_MODELS'

RENAME_TARGETS : 
    matched_to_severe_hail_0km : 'Severe Hail' 
    matched_to_tornado_0km     : 'Tornado' 
    matched_to_severe_wind_0km : 'Severe Wind'
                    
MODEL_NAMES : [
               'LogisticRegression', 
]
                 
TARGETS : [
           'wind_severe_0km',
           'hail_severe_0km',
          ] 

ENS_VARS  : [ 'uh_0to2_instant',
              'uh_2to5_instant',
              'wz_0to2_instant',
              'comp_dz',
              'ws_80',
              'w_up',
              'hailcast',
              'w_1km',
              'w_down',
              '10-500m_bulkshear',
              'div_10m',
              'buoyancy',
              'ctt',
              'dbz_3to5', 
              'dbz_1to3', 
              'okubo_weiss',
              'dbz_1km', 
]

ENV_IN_ENS_VARS : [ 'freezing_level',]

ENV_VARS : [
              'theta_e',
              'u_10',
              'v_10',
              'temperature_850',
              'temperature_700',
              'temperature_500',
              'td_850',
              'td_700',
              'td_500',
              'mid_level_lapse_rate',
              'low_level_lapse_rate',
              'geo_hgt_850',
              'geo_hgt_500',
              'geo_hgt_700',
              'td_850',
              'td_700',
              'td_500',
              'QVAPOR_850',
              'QVAPOR_700',
              'QVAPOR_500',
              'qv_2',
]

SVR_VARS : [ 'srh_0to1',
             'srh_0to3',
             'srh_0to500',
             'cape_ml',
             'cin_ml',
             'shear_u_0to6',
             'shear_v_0to6',
             'shear_u_0to1',
             'shear_v_0to1',
             'shear_u_3to6',
             'shear_v_3to6',
             'stp', 
             'stp_srh0to500',
             'lcl_ml',
           ]

ENS_MIN_VARS : [ 'ctt',
             'buoyancy',
             'div_10m',
             'w_down',
             'okubo_weiss',
             ]

MORPHOLOGICAL_FEATURES : [
                          'area',
                          'eccentricity',
                          'extent',
                          'orientation',
                          'minor_axis_length',
                          'major_axis_length',
                          'intensity_max',
                          ]
                          
FEATURE_SUBSET_DICT :  
                   'wz_0to2_instant__time_max__amp_ens_mean' : 'vert_vort' 
                   'hailcast__time_max__amp_ens_mean' : 'hail_size'
                   'uh_2to5_instant__time_max__amp_ens_mean' : 'uh'  
                   'comp_dz__time_max__amp_ens_mean' : 'comp_refl'
                   'cape_ml__ens_mean__spatial_mean' : 'cape' 
                   
                   'dbz_3to5__time_max__amp_ens_mean' : 'dbz_3to5'
                   'w_up__time_max__amp_ens_mean' : 'updraft'
                   
                   'ws_80__time_max__amp_ens_mean' : '80m_wind_spd'
                   'major_axis_length' : 'major_axis_length' 
                   'minor_axis_length' : 'minor_axis_length' 
                   'low_level_lapse_rate__ens_mean__spatial_mean' : '0-3km_lapse_rate' 
                   'mid_level_lapse_rate__ens_mean__spatial_mean' : '500-700mb_lapse_rate'
                 

ROUNDING : 
    'vert_vort' : 4
    'hail_size' : 2
    'uh' : 0
    'comp_refl' : 0 
    'cape' : 0
    'dbz_3to5' : 0 
    'updraft': 1 
    '80m_wind_spd' : 0
    'major_axis_length' : 0 
    'minor_axis_length' : 0
    '0-3km_lapse_rate' : 2
    '500-700mb_lapse_rate' : 2