#######################################
# MACHINE LEARNING CONFIGURATION YAML
#######################################

UH_THRESHS : [ 50,  60,  70,  80,  90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250]
WIND_THRESHS : [30, 35, 40, 45, 50, 55, 60, 65, 70]
HAIL_THRESHS : [0.5 , 0.75, 1.  , 1.25, 1.5]

# (in grid points) 
NMEP_SIZES : [0, 3, 5, 9]

BASELINE_VARS : 
    tornado : 'uh_probs_>180_prob_max'
    severe_hail : 'hail_probs_>1.0_prob_max'
    severe_wind : 'wnd_probs_>40_prob_max'
    
ML_MODEL_PATH : '../models/'

RENAME_TARGETS : 
    matched_to_severe_hail_0km : 'Severe Hail' 
    matched_to_tornado_0km     : 'Tornado' 
    matched_to_severe_wind_0km : 'Severe Wind'
                    
MODEL_NAMES : ['RandomForest', 
               'LogisticRegression', 
               'Baseline'
              ]
TARGETS : ['tornado', 
           'severe_hail', 
           'severe_wind'
          ] 

ENS_VARS  : [ 'uh_0to2_instant',
              'uh_2to5',
              'wz_0to2_instant',
              'comp_dz',
              'ws_80',
              'w_up',
              'hailcast',
              'w_1km',
              'w_down',
              '10-500m_bulkshear',
              'div_10m',
              'buoyancy',
              'ctt',
              'dbz_3to5', 
              'dbz_1to3', 
              'okubo_weiss'
]

ENV_IN_ENS_VARS : [ 'freezing_level',]

ENV_VARS : [
              'theta_e',
              'u_10',
              'v_10',
              'temperature_850',
              'temperature_700',
              'temperature_500',
              'td_850',
              'td_700',
              'td_500',
              'mid_level_lapse_rate',
              'low_level_lapse_rate',
              'geo_hgt_850',
              'geo_hgt_500',
              'geo_hgt_700',
              'QVAPOR_850',
              'QVAPOR_700',
              'QVAPOR_500',
              'qv_2',
]

SVR_VARS : [ 'srh_0to1',
             'srh_0to3',
             'srh_0to500',
             'cape_ml',
             'cin_ml',
             'shear_u_0to6',
             'shear_v_0to6',
             'shear_u_0to1',
             'shear_v_0to1',
             'shear_u_3to6',
             'shear_v_3to6',
             'stp', 
             'stp_srh0to500',
             'lcl_ml',
           ]

ENS_MIN_VARS : [ 'ctt',
             'buoyancy',
             'div_10m',
             'w_down'
             ]

MORPHOLOGICAL_FEATURES : [
                          'area',
                          'eccentricity',
                          'extent',
                          'orientation',
                          'minor_axis_length',
                          'major_axis_length', 
                          ]
    
RESAMPLE_DICT : 
    first_hour : 
        tornado       :
            RandomForest      : 'under'
            LogisticRegression: 'under'
            XGBoost           : 'under'
        severe_hail   :
            RandomForest      : 'under'
            LogisticRegression: 'under'
            XGBoost           : None
        severe_wind :
            RandomForest      : None
            LogisticRegression: 'under'
            XGBoost'           : None

    second_hour: 
        tornado :
            RandomForest      : 'under'
            LogisticRegression: None
            XGBoost           : 'under'
        severe_hail :
            RandomForest      : None
            LogisticRegression: None
            XGBoost           : None
        severe_wind :
            RandomForest      : 'under'
            LogisticRegression: None
            XGBoost           : None
       
